-- DonorBridge PostgreSQL DDL (logical 3NF model from relational-schema-3nf.html)

BEGIN;

DROP TABLE IF EXISTS query_execution_log CASCADE;
DROP TABLE IF EXISTS transplant CASCADE;
DROP TABLE IF EXISTS match_candidate CASCADE;
DROP TABLE IF EXISTS blood_unit CASCADE;
DROP TABLE IF EXISTS blood_donation CASCADE;
DROP TABLE IF EXISTS organ_offer CASCADE;
DROP TABLE IF EXISTS blood_request_details CASCADE;
DROP TABLE IF EXISTS organ_request_details CASCADE;
DROP TABLE IF EXISTS request CASCADE;
DROP TABLE IF EXISTS blood_inventory_location CASCADE;
DROP TABLE IF EXISTS medical_record CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS donor CASCADE;
DROP TABLE IF EXISTS intent_detection CASCADE;
DROP TABLE IF EXISTS chat_message CASCADE;
DROP TABLE IF EXISTS chat_session CASCADE;
DROP TABLE IF EXISTS sql_template CASCADE;
DROP TABLE IF EXISTS hospital CASCADE;

CREATE TABLE hospital (
    hospital_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    contact TEXT NOT NULL
);

CREATE TABLE patient (
    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id INTEGER NOT NULL REFERENCES hospital (hospital_id) ON DELETE RESTRICT,
    full_name TEXT NOT NULL,
    age INTEGER NOT NULL CHECK (age >= 0 AND age <= 150),
    gender TEXT NOT NULL,
    blood_group TEXT NOT NULL,
    contact_info TEXT NOT NULL,
    risk_score NUMERIC(5, 2) NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE medical_record (
    record_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patient (patient_id) ON DELETE CASCADE,
    diagnosis TEXT NOT NULL,
    severity_level TEXT NOT NULL,
    stage TEXT NOT NULL,
    hemoglobin_level NUMERIC(6, 2),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE donor (
    donor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id INTEGER NOT NULL REFERENCES hospital (hospital_id) ON DELETE RESTRICT,
    full_name TEXT NOT NULL,
    age INTEGER NOT NULL CHECK (age >= 0 AND age <= 150),
    blood_group TEXT NOT NULL,
    donor_type TEXT NOT NULL,
    contact_info TEXT NOT NULL,
    availability_status TEXT NOT NULL,
    eligibility_status TEXT NOT NULL,
    last_donation_date DATE
);

CREATE TABLE request (
    request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patient (patient_id) ON DELETE RESTRICT,
    hospital_id INTEGER NOT NULL REFERENCES hospital (hospital_id) ON DELETE RESTRICT,
    request_type TEXT NOT NULL CHECK (request_type IN ('BLOOD', 'ORGAN')),
    urgency_level INTEGER NOT NULL CHECK (urgency_level >= 1 AND urgency_level <= 5),
    status TEXT NOT NULL,
    request_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blood_request_details (
    request_id INTEGER PRIMARY KEY REFERENCES request (request_id) ON DELETE CASCADE,
    blood_group_required TEXT NOT NULL,
    units_required INTEGER NOT NULL CHECK (units_required > 0),
    required_by TIMESTAMP NOT NULL
);

CREATE TABLE organ_request_details (
    request_id INTEGER PRIMARY KEY REFERENCES request (request_id) ON DELETE CASCADE,
    organ_type_required TEXT NOT NULL,
    max_wait_time_days NUMERIC(8, 1) NOT NULL,
    hla_notes TEXT
);

COMMENT ON TABLE request IS
    'Blood requests pair only with blood_request_details; organ only with organ_request_details. PostgreSQL CHECK cannot '
    'reference child rows — enforce with transactions in the app/proc layer (seed obeys this).';

CREATE TABLE blood_donation (
    blood_donation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id INTEGER NOT NULL REFERENCES donor (donor_id) ON DELETE RESTRICT,
    donation_date TIMESTAMP NOT NULL,
    quantity_donated_ml INTEGER NOT NULL CHECK (quantity_donated_ml >= 0),
    outcome TEXT NOT NULL
);

CREATE TABLE blood_unit (
    blood_unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blood_donation_id INTEGER NOT NULL REFERENCES blood_donation (blood_donation_id) ON DELETE RESTRICT,
    blood_group TEXT NOT NULL,
    volume_ml INTEGER NOT NULL CHECK (volume_ml >= 0),
    expiry_date DATE NOT NULL,
    unit_status TEXT NOT NULL
);

CREATE OR REPLACE FUNCTION fn_blood_unit_expiry_ge_donation()
RETURNS TRIGGER AS $$
DECLARE donated_on DATE;
BEGIN
    SELECT blood_donation.donation_date::date
    INTO donated_on
    FROM blood_donation
    WHERE blood_donation.blood_donation_id = NEW.blood_donation_id;

    IF donated_on IS NULL THEN
        RAISE EXCEPTION 'blood_donation_id % not found', NEW.blood_donation_id;
    END IF;
    IF NEW.expiry_date < donated_on THEN
        RAISE EXCEPTION 'expiry_date must be >= donation_date for blood donation %',
            NEW.blood_donation_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_blood_unit_expiry_ge_donation
BEFORE INSERT OR UPDATE OF expiry_date, blood_donation_id ON blood_unit
FOR EACH ROW
EXECUTE FUNCTION fn_blood_unit_expiry_ge_donation();

CREATE TABLE blood_inventory_location (
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id INTEGER NOT NULL REFERENCES hospital (hospital_id) ON DELETE CASCADE,
    blood_group TEXT NOT NULL,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (hospital_id, blood_group)
);

CREATE TABLE organ_offer (
    organ_offer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id INTEGER NOT NULL REFERENCES donor (donor_id) ON DELETE RESTRICT,
    organ_type TEXT NOT NULL,
    availability_status TEXT NOT NULL,
    retrieval_date TIMESTAMP,
    medical_clearance TEXT NOT NULL
);

CREATE TABLE match_candidate (
    match_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES request (request_id) ON DELETE CASCADE,
    match_type TEXT NOT NULL CHECK (match_type IN ('BLOOD', 'ORGAN')),
    blood_unit_id INTEGER REFERENCES blood_unit (blood_unit_id) ON DELETE SET NULL,
    organ_offer_id INTEGER REFERENCES organ_offer (organ_offer_id) ON DELETE SET NULL,
    compatibility_score NUMERIC(4, 3) NOT NULL CHECK (compatibility_score >= 0 AND compatibility_score <= 1),
    priority_level TEXT NOT NULL,
    match_status TEXT NOT NULL,
    match_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT match_blood_xor_organ_chk CHECK (
        (
            match_type = 'BLOOD'
            AND blood_unit_id IS NOT NULL
            AND organ_offer_id IS NULL
        )
        OR (
            match_type = 'ORGAN'
            AND organ_offer_id IS NOT NULL
            AND blood_unit_id IS NULL
        )
    )
);

CREATE TABLE transplant (
    transplant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL REFERENCES match_candidate (match_id) ON DELETE RESTRICT,
    transplant_date TIMESTAMP NOT NULL,
    surgeon_name TEXT NOT NULL,
    outcome TEXT NOT NULL,
    UNIQUE (match_id)
);

CREATE TABLE chat_session (
    chat_session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id INTEGER NOT NULL REFERENCES hospital (hospital_id) ON DELETE CASCADE,
    user_role TEXT NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sql_template (
    template_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_code TEXT NOT NULL UNIQUE,
    sql_text TEXT NOT NULL,
    allowed_params TEXT NOT NULL,
    active_flag BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE chat_message (
    message_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_session_id INTEGER NOT NULL REFERENCES chat_session (chat_session_id) ON DELETE CASCADE,
    sender_type TEXT NOT NULL,
    message_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE intent_detection (
    intent_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES chat_message (message_id) ON DELETE CASCADE,
    template_id INTEGER NOT NULL REFERENCES sql_template (template_id) ON DELETE RESTRICT,
    confidence_score NUMERIC(4, 3) NOT NULL CHECK (confidence_score >= 0 AND confidence_score <= 1),
    detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (message_id)
);

CREATE TABLE query_execution_log (
    execution_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_id INTEGER NOT NULL REFERENCES intent_detection (intent_id) ON DELETE CASCADE,
    param_json TEXT,
    execution_status TEXT NOT NULL,
    rows_returned INTEGER NOT NULL CHECK (rows_returned >= 0),
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id INTEGER REFERENCES request (request_id) ON DELETE SET NULL,
    match_id INTEGER REFERENCES match_candidate (match_id) ON DELETE SET NULL,
    inventory_id INTEGER REFERENCES blood_inventory_location (inventory_id) ON DELETE SET NULL
);

COMMENT ON COLUMN blood_inventory_location.blood_group IS 'No aggregate unit counts stored (3NF).';

COMMIT;
